##
## The Golr config that will be used for the majority of associations in Monarch
##
## The model is roughly OBAN: https://github.com/jamesmalone/OBAN
##
## Note: initial implementation - fields will change in future
##
## This schema is a generalization of the one used for GO/AmiGO 2. See: https://github.com/geneontology/amigo/blob/master/metadata/ann-config.yaml
## A few points are worth bearing in mind when aligning the schema:
##
##  * GO sometimes uses standard terms like 'source' a little differently than standards like DC
##  * The OBAN 'subject' is always a bioentity (e.g. gene/product, complex, phylo tree node) in GO
##  * The OBAN 'object' is always a class in GO
##  * GO uses various ad-hoc fields such as 'secondary taxon' that would not be applicable here
##
##
##
##
id: generic_association
schema_generating: true
description: Associations following OBAN model
display_name: Annotations
document_category: generic_association
weight: 20

## For search
boost_weights: subject^2.0 subject_label^1.0 object^2.0 object_label^1.0

## Results table, horizontal
result_weights: subject^7.0 subject_category^6.2 subject_taxon^6.5 relation^6.0  object^5.0 object_category^4.5 object_taxon^4.2 evidence^4.0 source^3.5 is_defined_by^3.0

## Ordering of facets, vertical
filter_weights: subject_taxon_label^7.5 object_taxon_label^4.7

## SOLR FIELD DEFINITIONS

fields:

  - id: id
    description: "A unique identifier (CURIE) for the association. Optional."
    display_name: Association id
    type: string
    property: []
    
  - id: association_type
    description: "Label describing the assocation. Optional."
    display_name: Association type
    type: string
    property: []


## SUBJECT

  - id: subject
    description: "The CURIE for oban:association_has_subject. May be disease, variant, gene, person, ...."
    display_name: Subject
    type: string
    property: []

  - id: subject_label
    description: "Label for association_subject. This will always be rdfs:label. Conventions may vary as to what goes in the label. For genes will be symbol, but we may choose to uniquify by prefixing with species"
    display_name: Subject
    type: string
    property: []
  
  - id: subject_eq
    description: "Reflexive equivalent/same as closure"
    display_name: Subject Equivalents
    type: string
    cardinality: multi
    property: []

  - id: subject_closure
    description: "Reflexive closure of association_has_subject. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of"
    display_name: Subject (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: subject_closure_label
    description: "Labels for subject_closure."
    display_name: Subject (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: subject_category
    description: "Category of association.subject. Examples: gene, protein, disease, variant"
    display_name: Subject category
    type: string
    property: []

  - id: subject_category_label
    description: "Label for association_subject_category"
    display_name: Subject category
    type: string
    property: []

  - id: subject_taxon
    description: "Taxonomic class of the subject. This is typically a CURIE of the form NCBITaxon:nnnn."
    display_name: Subject Taxon
    type: string
    property: []

  - id: subject_taxon_label
    description: "Label of taxon."
    display_name: Subject Taxon
    type: string
    property: []

  - id: subject_taxon_closure
    description: "Reflexive closure of taxon. ALWAYS up SubClassOf."
    display_name: Taxon
    type: string
    cardinality: multi
    property: []

  - id: subject_taxon_closure_label
    description: "Labels for taxon_closure."
    display_name: Taxon
    type: string
    cardinality: multi
    property: []

  - id: subject_gene
    description: "Gene related to the subject."
    display_name: Subject Gene
    type: string
    property: []

  - id: subject_gene_label
    description: "Label of the gene."
    display_name: Subject Gene
    type: string
    property: []

  - id: subject_gene_closure
    description: "Reflexive closure of gene."
    display_name: Gene
    type: string
    cardinality: multi
    property: []

  - id: subject_gene_closure_label
    description: "Labels for gene_closure."
    display_name: Gene
    type: string
    cardinality: multi
    property: []

  - id: subject_ortholog_closure
    description: "Reflexive closure of orthology."
    display_name: Ortholog
    type: string
    cardinality: multi
    property: []

## RELATIONSHIP BETWEEN SUBJECT AND OBJECT

  - id: relation
    description: "A relationship type that connects the subject with object."
    display_name: Relationship
    type: string
    property: []

  - id: relation_label
    description: "Label for association_relation"
    display_name: Relationship
    type: string
    property: []

  - id: relation_closure
    description: "SubPropertyOf reflexive closure for association_relation"
    display_name: Relationship
    type: string
    cardinality: multi
    property: []

  - id: relation_closure_label
    description: "labels for association_relation_closure"
    display_name: Relationship
    type: string
    cardinality: multi
    property: []

  - id: qualifier
    description: "Association qualifier." # TBD: NEGATION should probably be handled differently somehow
    display_name: Qualifier
    type: string
    cardinality: multi
    property: []

## OBJECT

  - id: object
    description: "The CURIE for oban:association_has_object. This is often, but not always an ontology class. E.g. for a gene-gene interaction it is an (arbitrary) member of the pair."
    display_name: Object
    type: string
    property: []

  - id: object_label
    description: "Label for association_object."
    display_name: Object
    type: string
    property: []
    
  - id: object_eq
    description: "Reflexive equivalent/same as closure"
    display_name: Object Equivalents
    type: string
    cardinality: multi
    property: []

  - id: object_closure
    description: "Reflexive closure of association_has_object. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of"
    display_name: Object (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: object_closure_label
    description: "Labels for object_class_closure."
    display_name: Object (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: object_category
    description: "Category of association.object. Examples: phenotype, function, process, location, tissue, gene. In GO this is called aspect"
    display_name: Object type
    type: string
    property: []

  - id: object_category_label
    description: "Label for association_object_category"
    display_name: Object type
    type: string
    property: []

  - id: object_taxon
    description: "Taxonomic class of the object. This is typically a CURIE of the form NCBITaxon:nnnn. This field may be unfilled when used with certain categories"
    display_name: Object Taxon
    type: string
    property: []

  - id: object_taxon_label
    description: "Label of taxon."
    display_name: Object Taxon
    type: string
    property: []

  - id: object_taxon_closure
    description: "Reflexive closure of taxon. ALWAYS up SubClassOf."
    display_name: Object Taxon
    type: string
    cardinality: multi
    property: []

  - id: object_taxon_closure_label
    description: "Labels for taxon_closure."
    display_name: Object Taxon
    type: string
    cardinality: multi
    property: []

  - id: object_gene
    description: "Gene related to the subject."
    display_name: Object Gene
    type: string
    property: []

  - id: object_gene_label
    description: "Label of the gene."
    display_name: Object Gene
    type: string
    property: []

  - id: object_gene_closure
    description: "Reflexive closure of gene."
    display_name: Gene
    type: string
    cardinality: multi
    property: []

  - id: object_gene_closure_label
    description: "Labels for gene_closure."
    display_name: Gene
    type: string
    cardinality: multi
    property: []

## ASSOCIATION-LEVEL INFORMATION

  - id: source
    description: "References provided as evidence for a single association in the assertion chain. The assertion may be derived from connecting data from multiple sources, or multiple sources may corroborate the same assertion. References are collected from each source used in this chain when available."
    display_name: Reference
    type: string
    cardinality: multi
    property: []
    
  - id: source_count
    description: "Number of sources for association"
    display_name: source_count
    type: integer
    cardinality: single
    property: []
    searchable: false

  - id: source_label
    description: "Label for source"
    display_name: Object
    type: string
    cardinality: multi
    property: []

  - id: source_closure
    description: "CURIEs for source_closure"
    display_name: Object (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: source_closure_label
    description: "Labels for source_closure"
    display_name: Object (Inferred)
    type: string
    cardinality: multi
    property: []

  - id: evidence_graph
    description: "Evidence graph"
    display_name: Evidence graph formatted as graphson
    type: string
    property: []
    searchable: false
    indexed: false

  - id: evidence
    description: "Evidence type. In Monarch we may have a chain of assertions that link two entites/terms. This is a list of all evidence types used in that chain."
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []

  - id: evidence_label
    description: "Closure for evidence_type. Always SubClassof"
    display_name: Evidence label
    type: string
    cardinality: multi
    property: []

  - id: evidence_closure
    description: "Closure for evidence_type. Always SubClassof"
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []

  - id: evidence_closure_label
    description: "List of CURIES of all entities that form part of the evidence graph."
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []

  - id: evidence_object
    description: "List of CURIES of all entities that form part of the evidence graph."
    display_name: Evidence from
    type: string
    cardinality: multi
    property: []

  - id: evidence_object_label
    description: "evidence object label"
    display_name: Evidence label
    type: string
    cardinality: multi
    property: []

  - id: evidence_object_closure
    description: "Closure for evidence object"
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []

  - id: evidence_object_closure_label
    description: "List of CURIES of all entities that form part of the evidence closure."
    display_name: Evidence
    type: string
    cardinality: multi
    property: []

  - id: evidence_main_object
    description: "A list of CURIEs for the primary object that supports an association. This will be a subset of evidence_object."
    display_name: Evidence from (main)
    type: string
    cardinality: multi
    property: []

  - id: evidence_main_object_label
    description: "evidence main object label"
    display_name: Evidence main label
    type: string
    cardinality: multi
    property: []

  - id: is_defined_by
    description: "Associations are obtained from the source(s) listed. More than one source indicates the association may be derived from connecting data from multiple sources, or multiple sources have corroborated the same assertion."
    display_name: Source
    type: string
    cardinality: multi
    property: []

  - id: onset
    description: "Classes that describe typical modifiers of clinical symptoms. For example the speed of progression, the variablity or the onset. "
    display_name: Clinical Modifier
    type: string
    property: []

  - id: onset_label
    description: "Classes that describe typical modifiers of clinical symptoms. For example the speed of progression, the variablity or the onset. "
    display_name: Clinical Modifier
    type: string
    property: []

  - id: onset_closure
    description: "Classes that describe typical modifiers of clinical symptoms. For example the speed of progression, the variablity or the onset. "
    display_name: Clinical Modifier
    type: string
    cardinality: multi
    property: []

  - id: onset_closure_label
    description: "Classes that describe typical modifiers of clinical symptoms. For example the speed of progression, the variablity or the onset. "
    display_name: Clinical Modifier
    type: string
    cardinality: multi
    property: []

  - id: frequency
    description: "Frequency with that patients do show a particular clinical feature."
    display_name: Frequency
    type: string
    property: []

  - id: frequency_label
    description: "Frequency with that patients do show a particular clinical feature."
    display_name: Frequency
    type: string
    property: []

  - id: frequency_closure
    description: "Frequency with that patients do show a particular clinical feature."
    display_name: Frequency
    type: string
    cardinality: multi
    property: []

  - id: frequency_closure_label
    description: "Frequency with that patients do show a particular clinical feature."
    display_name: Frequency
    type: string
    cardinality: multi
    property: []
    
  - id: confidence_score
    description: "Confidence score for association"
    display_name: Confidence Score
    type: integer
    property: []
